### PR TITLE
Makefile and user permissions

### PR DESCRIPTION
**Pull request by Demoli**
Build docker with `make docker-build`

### CODE REVIEW

**Comment by Demoli** [comment]
Notes:
PHP 7.4 GD fails, replace the gd build with in your installed docker files
`&& docker-php-ext-configure gd --with-freetype --with-jpeg \`

When doing a  `docker exec` to the FPM container you'll get `bash: /root/.bashrc: Permission denied` perhaps ZSH related?

**Comment by Demoli** [comment]
Docker is installed as root, but should be installed as local user.

**Comment by Demoli** [comment]
@valguss 
Actually the issue seems to be installing pretissimo globally, which then throws an error when you run composer as the local user.
Suggest removing pretissimo and installing from inside the container.

**Comment by valguss** [comment]
#17 should take care of the bash permissions issue

**Pull request merged**
